version: "3.8"
services:
  leecher:
    image: swarm-registry:5000/shotgrid-leecher_v0.0.8
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MODULE_NAME: shotgrid_leecher.main
      MAX_WORKERS: ${MAX_WORKERS}
      PORT: 8080
    ports:
      - "8090:8080"
    deploy:
      placement:
        constraints: [node.hostname == swarm-worker2]
      mode: 'replicated'
      replicas: 1
    dns:
      - 8.8.8.8
      - 9.9.9.9
