version: "3.8"
services:
  leecher:
    image: '$AWS_ID$.dkr.ecr.eu-west-3.amazonaws.com/ellipse/swarm_registry:shotgrid_leecher_api_v0.0.9'
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MODULE_NAME: shotgrid_leecher.main
      MAX_WORKERS: ${MAX_WORKERS}
      PORT: 8080
    ports:
      - "8090:8080"
    deploy:
      placement:
        constraints: [node.hostname == swarm-worker2]
      mode: 'replicated'
      replicas: 1
    dns:
      - 8.8.8.8
      - 9.9.9.9
